Updated descriptions Royal Knight Fighter subclass abilities
SolastaMods/SolastaUnfinishedBusiness pull request #2653
Opened 2023-03-05 00:05 UTC by LunaKB

- Changed descriptions for the following Royal Knight Fighter subclass abilities:
-- Rallying Cry
-- Inspiring Surge
- Corrected title for Inspiring Surge power. It used to say "Preserve Life". It now says "Inspiring Surge".

This should provide clarity to the players.

2023-03-05 00:39 UTC, ThyWoof requested changes

2023-03-05 00:39 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> +            .Create()
Why are you touching these effects?

2023-03-05 00:42 UTC, ThyWoof requested changes

2023-03-05 00:42 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> -            .Create(PowerDomainLifePreserveLife, "PowerRoyalKnightInspiringSurge")
Why change this power?

2023-03-05 00:42 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> -                .Create(PowerDomainLifePreserveLife.EffectDescription)
Why change this effect?

2023-03-05 08:02 UTC, Pikachar2 commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> +            .Create()
The ability effectively gives Action Surge to another character. It has nothing to do with Preserve Life. Which is the Life Cleric's Channel Divinity. To the best of our knowledge it seems that it's just a description/title that's setup as kind of a template in these instances. And on top of that, it was named as Preserve Life when looking for the ability in Combat/from the Action bar.

2023-03-05 14:43 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> +            .Create()
These have nothing to do with descriptions but the template we copy behavior from. I don’t believe it should be changed. Only the translations

2023-03-05 18:35 UTC, LunaKB commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> -            .Create(PowerDomainLifePreserveLife, "PowerRoyalKnightInspiringSurge")
When you select the power as a bonus action, the name for power was incorrect. Removing this makes the text correct. Here's what the UI looks like without the fix:

![UnfinishedBusiness-pull2653](https://user-images.githubusercontent.com/21045542/222979107-3cac3fd5-6656-4749-91ac-bfbaae5e2857.PNG)

2023-03-05 18:41 UTC, LunaKB commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> -                .Create(PowerDomainLifePreserveLife.EffectDescription)
This was changed in the effort to get the text for the power Inspiring Surge to no longer say "Preserve Life". I'll update this with this put back.

2023-03-05 18:41 UTC, LunaKB commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> +            .Create()
This was changed in the effort to get the text for the power Inspiring Surge to no longer say "Preserve Life". I'll update this with this put back.

2023-03-05 18:49 UTC, LunaKB commented
Updated pull request according to comments.

2023-03-05 19:14 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/MartialRoyalKnight.cs
> -                .Create(PowerDomainLifePreserveLife.EffectDescription)
this is an effect description. It's nothing to do with the description on screen.

2023-03-05 20:00 UTC, ThyWoof commented
I confirm it’s indeed showing the wrong title even though the json dump says otherwise. Will look into it

2023-03-05 23:04 UTC, LunaKB commented
Alright, if it will be fixed later, I'll update with the preserve life put back.

2023-03-05 23:06 UTC, LunaKB commented
Updated pull request according to comments.

2023-03-07 04:17 UTC, merged

2023-03-07 04:19 UTC, ThyWoof commented
found out what the issue was. PowerDomainLife also had a short title description set. This was causing the wrong title to display.