Initial Commit to Blast Surge.
SolastaMods/SolastaUnfinishedBusiness pull request #3510
Opened 2023-06-13 05:32 UTC by HIEROT

Known issues:
Absent of Subclass Sigil and localized string automation and some battle logs.
TL;DR: save in the turn with Blast Reload causes minor problems.
Status of casted cantrip is unserializable though latent in memory, so if the memory is lost (say you save between cast main cantrip, restart game and load) you lose cast bonus cantrip). Also if you sl game without end your turn, the cached cantrips are still there and will prevent you from adding Blast Reload if it's not already there until your next turn end, and granting you cast bonus cantrip if you already have Blast Reload, though haven't yet cast main cantrips.

2023-06-13 05:34 UTC, HIEROT commented
Oh forget too add ranged spell attack no disadvantage within enemy melee range.

2023-06-13 06:33 UTC, HIEROT commented on SolastaUnfinishedBusiness/Subclasses/PatronEldritchSurge.cs
> +        private List<SpellDefinition> usedCantrips = new List<SpellDefinition>();
This private structure is unserielizable and causes minor problems.

2023-06-13 14:24 UTC, HIEROT commented
New Bing is truely my savior!
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/2b311b1a-5d3e-48f4-823a-6f9e2fef84cb)

2023-06-13 17:28 UTC, HIEROT commented
@ThyWoof How to add png resource? I used default VS resx editor to import image, but I cannot edit its type to byte[]. Or Any automation script to run this?

2023-06-13 20:11 UTC, ThyWoof commented
> @ThyWoof How to add png resource? I used default VS resx editor to import image, but I cannot edit its type to byte[]. Or Any automation script to run this?

I manually edit resources.resx and then clean project.

2023-06-13 20:12 UTC, ThyWoof commented
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaUnfinishedBusiness/Properties/Resources.resx

2023-06-13 20:31 UTC, HIEROT commented
> https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaUnfinishedBusiness/Properties/Resources.resx

Alright, having done the same... Now this subclass is completely implemented, excluding language localization other than EN and zh-CN.

2023-06-14 19:31 UTC, EnderWiggin commented on SolastaUnfinishedBusiness/Api/GameExtensions/RulesetCharacterExtensions.cs
> +            // Return 1 is very bad practice here! Making function name semantics different from actual effect!
While I agree that returning 1 here is bad practice, this change will break other features, unless there's according fix in other relevant places.

2023-06-14 22:10 UTC, HIEROT commented on SolastaUnfinishedBusiness/Api/GameExtensions/RulesetCharacterExtensions.cs
> +            // Return 1 is very bad practice here! Making function name semantics different from actual effect!
Of course I noticed the comment there but I just didn't figure out where this is needed,  so didn't take care of it_(:з」∠)_

2023-06-16 10:58 UTC, HIEROT commented
@EnderWiggin I thought there is a serielizable property to hold cast spells and the like to prevent stautus lost between sl and restart game. Do you have an idea? Thanks.

2023-06-19 03:40 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Api/GameExtensions/RulesetCharacterExtensions.cs
> +            // Return 1 is very bad practice here! Making function name semantics different from actual effect!
this bad practice was introduce to support gambits granted from feat to non Tactician.

2023-06-19 04:09 UTC, ThyWoof requested changes

2023-06-19 07:50 UTC, HIEROT commented on SolastaUnfinishedBusiness/CustomBuilders/InvocationsBuilders.cs
> +                action.ActionDefinition.ActionScope == ActionDefinitions.ActionScope.Battle)
To better comply with other similar check for whether action is in combat. Besides, checking character on guard will result no extra buff applied when the party happens to be caught on fight, because at that time the party is no more on guard.

2023-06-19 07:55 UTC, HIEROT commented on SolastaUnfinishedBusiness/Api/GameExtensions/RulesetCharacterExtensions.cs
> +            // Return 1 is very bad practice here! Making function name semantics different from actual effect!
I use this function to calculate the subclass level of Eldritch Surge to determine number of beams. If you are other subclass warlock,this will return 1 and causes you only having one beam. If it's inconvenient to modify here, it's fine to just add a private function handling this.

2023-06-19 14:29 UTC, ThyWoof approved these changes

2023-06-19 14:29 UTC, merged