Race Wendigo
SolastaMods/SolastaUnfinishedBusiness pull request #3514
Opened 2023-06-13 15:53 UTC by otearaisu

### Wendigo
#### Level 1
* Strength +2
* Dexterity +1
* Stalker - You are proficient in Stealth
* Powerful Build - You count your size as Large when determining your carrying capacity.
* Natural Lunger - Your melee range increases by 5 feet. Does not stack with Lunger.
* Sucker Punch - On the first round of combat, if you hit a creature with an attack roll and it's initiative is lower than you, the creature takes additional 2d6 damage.

2023-06-14 23:48 UTC, ThyWoof requested changes
Also that PNG looks ugly, lol. Sad we lost a very good graphics resource on the mod. Any changes you could try to use AI drawing software to achieve a better result. @HIEROT could guide you there.

2023-06-14 23:48 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Api/GameExtensions/EnumExtensions.cs
> +    TargetHasLowerInitiativeOnFirstRound = 9004
This is an old pattern in the mod that can be better accomplished with our interfaces. Please take a look at Roguish Slayer that has a very similar feature and try to follow that pattern. here: https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/f0f84219c08fbf961ad545fc647135a32e626e53/SolastaUnfinishedBusiness/Subclasses/RoguishSlayer.cs#L198

2023-06-15 00:31 UTC, otearaisu commented
> Also that PNG looks ugly, lol. Sad we lost a very good graphics resource on the mod. Any chances you could try to use AI drawing software to achieve a better result. @HIEROT could guide you there.

Sadly, the AI drawing software is not available in my region. I'll try to find if there are other sources though.

2023-06-15 00:31 UTC, otearaisu commented on SolastaUnfinishedBusiness/Api/GameExtensions/EnumExtensions.cs
> +    TargetHasLowerInitiativeOnFirstRound = 9004
Applied requested change.

2023-06-15 02:56 UTC, HIEROT commented
@otearaisu here you are.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/e0cffd44-93e1-4c0c-95bb-1c700c2bcd74)

2023-06-15 02:58 UTC, HIEROT commented
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/f350e343-1674-4e71-bbfb-ea7b1a762b16)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/916498f8-16da-43e0-b431-5626c394eced)

2023-06-15 02:59 UTC, HIEROT commented
Oh, I tried to improve them by adding more description.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/c6ae3bfe-441e-4b8e-ac0e-64ac0450f1ff)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/0e3e121d-770f-40d9-a94c-ab39b02a26b8)

2023-06-15 03:21 UTC, ThyWoof commented
Now we are talking

2023-06-15 04:33 UTC, HIEROT commented
I think this one is the best.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55292746/c6ae3bfe-441e-4b8e-ac0e-64ac0450f1ff)

2023-06-15 05:30 UTC, otearaisu commented
> I think this one is the best. ![image](https://user-images.githubusercontent.com/55292746/245980414-c6ae3bfe-441e-4b8e-ac0e-64ac0450f1ff.png)

Amazing! Thanks for this haha originally planned to draw it manually

2023-06-15 12:11 UTC, otearaisu commented
Updated both png and implementation now.

2023-06-15 19:14 UTC, ThyWoof approved these changes

2023-06-15 19:14 UTC, merged