Fix some missing sprites
SolastaMods/SolastaUnfinishedBusiness pull request #3693
Opened 2023-07-03 04:58 UTC by HIEROT

2023-07-03 05:28 UTC, ThyWoof requested changes

2023-07-03 05:28 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
This won’t make any change on sprites FYI. What is your goal here? For a sprite you need a proper text on condition as well as a sprite reference on SetGuiPresentation. Did you test this change?

2023-07-03 05:45 UTC, HIEROT commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
if you set it to false, this condition is completely hidden, including its spirit circling sprites

2023-07-03 05:49 UTC, HIEROT commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
But this fix has its limitation though, now it will show no content or something (cause i am not using english) at tooltip.
I think the missing of sprites is due to vanilla game code modification. If no content and hidden is set, the particle effect will also be hidden.

2023-07-03 05:50 UTC, HIEROT commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
but this change is tested.

2023-07-03 05:56 UTC, HIEROT commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
And oh I got the two concepts mixed up. I mean particle effects.

2023-07-03 13:57 UTC, ThyWoof requested changes

2023-07-03 13:57 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
undo this change on SetGuiPresentation so I can merge pls.

2023-07-04 00:36 UTC, HIEROT commented on SolastaUnfinishedBusiness/Spells/SpellBuildersLevel03.cs
> +                                .SetGuiPresentationNoContent(false)
OK

2023-07-04 03:14 UTC, ThyWoof approved these changes

2023-07-04 03:14 UTC, merged