Change Improved Abjuration to modify existing spell EffectForms
SolastaMods/SolastaUnfinishedBusiness pull request #5025
Opened 2024-11-01 20:37 UTC by BShennette

Initial version was copying power definition from the Hive Patron -- I didn't realize that was a one-time-use w/ no slot.
Now it modifies Counterspell and Dispel Magic spells for the caster. Vanilla log for dispel magic doesn't show an ability check, as a note.

Also, this change alerted me to a bug that I think is from Vanilla? You can select proxy effects to dispel (like _Wall of Fire_ or _Flaming Sphere_) and an animation plays, but the effect doesn't end up getting dispelled. Might be worth looking into (not that I'm aware of any enemies that use that kind of spell atm?)

2024-11-01 21:42 UTC, HiddenHax commented
Do Cloudkill, Insect Swarm and Black Tentacles count as proxies? If so, there are some casters that use these (Master Madracht and Mummy Lord iirc).

2024-11-02 02:19 UTC, ThyWoof requested changes

2024-11-02 02:19 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/WizardAbjuration.cs
> +            return EffectDescriptionBuilder
no need to build a new effect description here. we already take care of having a copy that is passed to this method. Also a good idea to have the effect form as a static field to avoid building every time.

2024-11-02 02:19 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/WizardAbjuration.cs
> +            return EffectDescriptionBuilder.Create(DispelMagic)
no need to build a new effect description here. we already take care of having a copy that is passed to this method. Also a good idea to have the effect form as a static field to avoid building every time.

2024-11-02 02:19 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/WizardAbjuration.cs
> +                        .SetBonusMode(AddBonusMode.None)
no need to set default values

2024-11-02 02:19 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/WizardAbjuration.cs
> +                        .SetBonusMode(AddBonusMode.None)
no need to set default values

2024-11-02 20:45 UTC, ThyWoof approved these changes

2024-11-02 20:46 UTC, merged