Enable InvocationPactBlade to use CHA for weapon attacks
SolastaMods/SolastaUnfinishedBusiness pull request #5067
Opened 2024-11-20 07:10 UTC by BShennette

and Fix Hexblade to work with InvocationPactBlade for 2H weapons.

2024 Pact of the Blade invocation also allows you to use CHA with the bonded weapon. I've added the same qualifier from Hexblade to the invocation.

I also fixed Hexblade condition only looking for the Pact of the Blade _feature_, which doesn't exist if you enable the 2024 Pact invocations option; it will now also consider the invocation.

![Untitled](https://github.com/user-attachments/assets/ffd8e8b4-9bd5-4f17-b4da-0ec6d110950a)

2024-11-20 15:44 UTC, ThyWoof requested changes

2024-11-20 15:44 UTC, ThyWoof commented on SolastaUnfinishedBusiness/Subclasses/PatronSoulBlade.cs
> +    public static bool CanWeaponBeEmpowered(RulesetAttackMode mode, RulesetItem item, RulesetCharacter character)
why Public?

2024-11-20 23:38 UTC, BShennette commented on SolastaUnfinishedBusiness/Subclasses/PatronSoulBlade.cs
> +    public static bool CanWeaponBeEmpowered(RulesetAttackMode mode, RulesetItem item, RulesetCharacter character)
Err... internal. Sorry, I confused that with protected and thought it wouldn't work.

2024-11-21 00:41 UTC, ThyWoof approved these changes

2024-11-21 00:41 UTC, merged